root_dir : !PLACEHOLDER # TODO adjust path
data_dir: !PLACEHOLDER  # TODO adjust path
save_output: true

datasets: !include:datasets_vpc2022_official_anon.yaml

results_dir: !PLACEHOLDER # TODO adjust path
pipeline: dsp

modules:
  anon_suffix: _dsp
  n_coeffs: 20
  mc_coeff_min: 0.5
  mc_coeff_max: 0.9
  winLengthinms: 20
  shiftLengthinms: 10
  seed: 0
  anon_level: spk
  anon_level_libri_360: utt
