root_dir : .
data_dir: ~/Projects/2022-voiceprivacychallenge/baseline/data
save_output: true

datasets: !include:datasets_vpc2022_official_anon.yaml

results_dir: !ref <root_dir>/exp/B2_anon/anon_speech
pipeline: !name:anonymization.pipelines.dsp_pipeline.DSPPipeline

modules:
  anon_suffix: _anon
  n_coeffs: 20
  mc_coeff_min: 0.5
  mc_coeff_max: 0.9
  winLengthinms: 20
  shiftLengthinms: 10
  seed: 0
  anon_level: spk
  anon_level_libri_360: utt
